// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.real.umssimulator;

import com.real.umssimulator.CancelRequest;

privileged aspect CancelRequest_Roo_JavaBean {
    
    public String CancelRequest.getReason() {
        return this.reason;
    }
    
    public void CancelRequest.setReason(String reason) {
        this.reason = reason;
    }
    
}
